name: CI/CD Pipeline for ProfitScout GPT

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: 'profitscout-lx6bb'
          workload_identity_provider: 'projects/469352939749/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use Google Cloud credentials
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/profitscout-lx6bb/profitscout-gpt/profitscout-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: profitscout-api
          region: us-central1
          image: us-central1-docker.pkg.dev/profitscout-lx6bb/profitscout-gpt/profitscout-api:${{ github.sha }}
          flags: '--allow-unauthenticated'
